describe('Test Actualizar Horario Medico', () => {
    it('Iniciar Sesion y actualizar un horario del medico', () => {
      cy.visit('http://localhost:5173/')
      cy.get(':nth-child(2) > .login__input').type('doctor2@gmail.com')
      cy.wait(1000)
      cy.get(':nth-child(3) > .login__input').type('Contraseña123')
      cy.wait(1000)
      cy.get('.button__text').click()
      cy.wait(1000)
      cy.get('.ml-0').should('have.text', 'Medicare')
      cy.wait(1000)
      cy.get('.me-auto > :nth-child(2)').click()
      cy.wait(1000)
      cy.get('.secondary-button').click()
      cy.wait(1000)
      cy.get(':nth-child(1) > :nth-child(4) > .select-dia').select('Martes')
      cy.wait(1000)
      cy.get(':nth-child(1) > :nth-child(5) > .form-control').type('10:00')
      cy.wait(1000)
      cy.get(':nth-child(1) > :nth-child(6) > .form-control').type('11:00')
      cy.wait(1000)
      cy.get(':nth-child(1) > :nth-child(7) > .primary-button').click()
      cy.wait(1000)

      cy.get('.swal2-confirm').click()
      cy.wait(1000)
      cy.get('#swal2-title').should('have.text', 'Éxito')
      cy.wait(1000)
      cy.get('.swal2-confirm').click()
    })
  })