name: continues integration

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  compilacion:
    runs-on: ubuntu-latest

    steps:
    - name: Clonando el repositorio
      uses: actions/checkout@v4